[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
# remappings（對應你的 import 路徑）
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@solvprotocol/contracts=lib/erc-3525/contracts"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Arbitrum 主網配置
[profile.arbitrum]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

# remappings（對應你的 import 路徑）
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@solvprotocol/contracts=lib/erc-3525/contracts"
]



# RPC 配置
[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

# 鏈配置
[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }